### ISSUE TITLE
TO-DO's

### ISSUE THREAD

**Issue by leslie-huang** [leslie-huang/stylest#2]
`stylest` to-do list:

- [ ] more smoothing options
- [ ] n-grams
- [ ] `quanteda` compatibility (major change)
- [ ] weighting (i.e. speeches by length)

I (Leslie) maintain this package but I am also a full time PhD student! I will try to get to all requests/issues/bugs/PRs ASAP.

**Comment by ArthurSpirling** [comment]
Should we switch out the load instructions in favor of the standard CRAN d/l, or is there some reason to keep the devtools version as preferred here?

**Comment by leslie-huang** [comment]
I will update the README and vignette!

**Comment by ArthurSpirling** [comment]
(Also, we should probably write a more involved vignette at some point, but that can wait for now)

**Comment by leslie-huang** [comment]
Both are updated on GitHub! 

Unfortunately the ones that are linked from the CRAN webpage ( https://cran.r-project.org/web/packages/stylest/vignettes/stylest-vignette.html and https://cran.r-project.org/web/packages/stylest/readme/README.html ) can't be updated until the next time I submit an updated package to CRAN -- they're included as-is in the package build.

**Comment by panoptikum** [comment]
Right now, I only see an easy option to extract the overall influential terms. Can I somehow extract those terms that are responsible for a speaker to be distinctive to others?

**Comment by leslie-huang** [comment]
@panoptikum Hi Felix, currently it is not possible to see the influence of terms disaggregated by speaker. Can you open a new issue for this feature request and we will add this in when we can?

**Comment by panoptikum** [comment]
@leslie-huang Sure, but before I do that for what do the numbers under in the "rate" data frame stand for (e.g. mod$rate)? Isn't that the influence or am I mistaken? I'm not fully aware of the functions of your package. If not, I'm happy to open a new feature request.

**Comment by leslie-huang** [comment]
@panoptikum model$rates contains the smoothed term usage rates, but this is not the same as term influence. We compute average term influence by taking the mean over the product of the de-meaned term frequency rate and each speaker's term frequency. It sounds like you want influence for speaker-term pairs and these are what go into average term influence.

Please feel free to include more details when you open a new issue -- we would like to keep requests, bugs etc organized instead of having a megathread about this package.
